### ISSUE TITLE
Missing 0 in PS2H Signature script

### ISSUE THREAD

**Issue by bodymindarts** [MaxHillebrand/LightningMultiSig#3]
Just a little nitpick in the witness script for P2WSH you add the needed `0` at the beginning:
```
Witness Script 0 <signature 1> …​ <signature M> M <Public Key 1> …​ <Public Key M> N CHECKMULTISIG
```
But you left it out of the section on SignatureScript:
```
SignatureScript: <Signature 1> …​ <Signature M> <redeem script>
```

Not a big deal, just something I noticed while scrolling through.

**Comment by MaxHillebrand** [comment]
Aaaah, that 0... :D
Thank you very much for noticing, it's fixed :)
